---
title: "Question 2 and 6"
author: "Daria Moiseeva"
date: "2023-11-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r reading data, include=FALSE}
library(readxl)
data <- read_xlsx("MUE.2022.for.LMU.xlsx")
data
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(gridExtra)
library(patchwork)
library(GGally)

```

```{r  Q2 }
# creating suitable table for 2nd question 
data.Q2 <- data %>%
  select(SERIAL,class,E002)%>%
# filter answers, that don't give any information about frequency of volunteering
  filter(E002 > -2) %>%
  filter(!is.na(E002)) %>%
# add a column with a grand total
  mutate(total=length(SERIAL))%>%
# add a column with marginal total for each class of size of company
  group_by(class) %>%
  mutate(class_total = length(class))%>%
# add a column with marginal total for each level of frequency of volunteering
  group_by(E002) %>%
  mutate(frequency_total = length(E002))%>%
# add a column with absolute frequencies for each case
  group_by(class,E002) %>%
  mutate(abs_frequency = length(E002)) %>%
# add a column with expected absolute frequencies for each case
  mutate(exp_abs_frequency = round((class_total*frequency_total)/total,
                                    digits = 2))%>%
# add a column with conditional relative frequency of the level of frequency of volunteering given the class of size of a company
  group_by(class,E002) %>%
  mutate(rel_frequency = abs_frequency / class_total)%>%
# leave only useful data
  select(-SERIAL)%>%
  distinct()%>%
# rearrange the frequency levels acceding(from "irregular" 
# to "more often than once a month")
  mutate(E002 = case_when(E002 == -1 ~ 1,
                          E002 == 1 ~ 5,
                          E002 == 2 ~ 4,
                          E002 == 3 ~ 3,
                          E002 == 4 ~ 2)) %>%
# arrange names of classes ascending
  mutate(class = case_when(class == "Kleine Unternehmen" ~ 1,
                           class == "Mittlere Unternehmen" ~ 2,
                           class == "Großunternehmen" ~ 3))

# calculate chi-squared test statistic(X^2) and corrected Pearson contingency coefficient(K*) to quantify the strength of correlation

chi_squared <-sum((data.Q2$abs_frequency-data.Q2$exp_abs_frequency)^2 /
                     data.Q2$exp_abs_frequency)
chi_squared

standardized_significance <- sqrt(chi_squared/(chi_squared + data.Q2$total[1])) /    sqrt((min(n_distinct(data.Q2$class),n_distinct(data.Q2$E002))-1)/ min(n_distinct(data.Q2$class),n_distinct(data.Q2$E002)))

standardized_significance

data.Q2 %>%
  arrange(E002,class) %>%
  ggplot(aes(x=class,y = rel_frequency, color=factor(E002), group = E002))+
  geom_point(size = 4) +
  geom_line(size = 2) +
  scale_x_continuous(breaks = c(1,2,3), labels=c("small","middle","big"))+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
  labs(x = "Size of a company",
       y = "Percent of companies ",
       title = "Frequency of corporate volunteering activities compared
to the size of a company") +
  theme_minimal()+
  theme(title=element_text(size = 15),
        axis.title = element_text(size = 15),
        axis.text= element_text(colour="black", size = 14),
        legend.text=element_text(size = 14),
        legend.title=element_text(size = 15))+
  scale_colour_brewer(name="Frequency of volunteering:",
                      breaks=c(1,2,3,4,5),
                      labels=c("irregular","once a year","once in a six months",                           "once per quarter","more often than once a month"),
                      palette = "Set1") +
  annotate(geom ="text",x = 2.5,y = 0.3,label=c("corrected Pearson
  contingency coefficient
  (0 <= K* <= 1)
  K* = 0.087"),size= 5)

ggsave("2question.jpeg",device = "jpeg",width = 9,height = 6)

```

```{r Q6.1 }
data.Q2 %>%
  arrange(E002,class) %>%
  ggplot(aes(x=class,y = abs_frequency, fill=factor(E002)))+
  geom_bar(position="fill",stat = "identity")+
  scale_x_continuous(breaks = c(1,2,3), labels=c("small","middle","big"))+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
  labs(x = "Size of a company",
       y = "Percent of companies",
       title = "Frequency of corporate volunteering activities compared
to the size of a company") +
  theme_minimal()+
  theme(title=element_text(size = 15),
        axis.title = element_text(size = 15),
        axis.text= element_text(colour="black", size = 14),
        legend.text=element_text(size = 14),
        legend.title=element_text(size = 15))+
  scale_fill_brewer(name="Frequency of volunteering:",
                      breaks=c(1,2,3,4,5),
                      labels=c("irregular","once a year","once in a six months",                           "once per quarter","more often than once a month"),
                      palette = "GnBu")

ggsave("6.1question.jpeg",device = "jpeg", width = 9, height = 6)
```



```{r Q6.2 }
# creating suitable table for 2nd question 
data.Q6 <- data %>%
  select(SERIAL,A003,E002,class)%>%
# filter answers, that don't give any information about frequency of volunteering
  filter(E002 > -2) %>%
  filter(A003 > 0) %>%
  filter(!is.na(E002)) %>%
# add a column with marginal total for each class of size of company
  group_by(A003) %>%
  mutate(industry_total = length(A003))%>%
# add a column with absolute frequencies for each case
  group_by(A003,E002) %>%
  mutate(abs_frequency = length(E002)) %>%
# add a column with conditional relative frequency of the level of frequency of volunteering given the class of size of a company
  group_by(A003,E002) %>%
  mutate(rel_frequency = abs_frequency / industry_total)%>%
# leave only useful data
  select(-SERIAL)%>%
  distinct()%>%
# rearrange the frequency levels acceding(from "irregular" 
# to "more often than once a month")
  mutate(E002 = case_when(E002 == -1 ~ 1,
                          E002 == 1 ~ 5,
                          E002 == 2 ~ 4,
                          E002 == 3 ~ 3,
                          E002 == 4 ~ 2)) %>%
  mutate(A003 = case_when(A003 == 1 ~ "Construction Industry",
                          A003 == 2 ~ "Mining / Metal",
                          A003 == 3 ~ "Education / Further Education", 
                          A003 == 4 ~ "Chemistry / Pharmaceuticals",
                          A003 == 5 ~ "Electrical Engineering",
                          A003 == 6 ~ "Energy / Water", 
                          A003 == 7 ~ "Vehicle Manufacturing / Supplier",
                          A003 == 8 ~ "Finance / Insurance", 
                          A003 == 9 ~ "Hospitality / Retail",
                          A003 == 10 ~ "Health / Social Services",
                          A003 == 11 ~ "Real Estate / Housing",
                          A003 == 12 ~ "Trade / Commerce", 
                          A003 == 13 ~ "Information Technology / Communication", 
                          A003 == 14 ~ "Art / Entertainment / Recreation",
                          A003 == 15 ~ "Agriculture / Forestry", 
                          A003 == 16 ~ "Mechanical Engineering",
                          A003 == 17 ~ "Food Industry", 
                          A003 == 18 ~ "Traffic / Logistics / Transportation",
                          A003 == 19 ~ "Other Service Industry", 
                          A003 == 20 ~ "Other Manufacturing Industry",
                          A003 == 21 ~ "Other Industry"))

data.Q6 %>%
  arrange(E002) %>%
  ggplot(aes(x=A003, y = abs_frequency, fill=factor(E002)))+
  geom_bar(position="fill",stat="identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
  labs(x = "Industry",
       y = "Percent of companies",
       title = "Distribution of frequency of corporate volunteering
across industries") +
  theme_minimal()+
  theme(title=element_text(size = 15),
        axis.title = element_text(size = 15),
        axis.text.x = element_text(colour="black",angle = 55, hjust = 1,size = 12),
        axis.text.y = element_text(colour="black",size = 12),
        legend.text= element_text(size = 14),
        legend.title=element_text(size = 15))+
  scale_fill_brewer(name="Frequency of volunteering:",
                      breaks=c(1,2,3,4,5),
                      labels=c("irregular","once a year","once in a six months",                           "once per quarter","more often than once a month"),
                      palette = "GnBu")

ggsave("6.2question.jpeg",device = "jpeg", width = 9, height = 6)

```

```{r Q6.3}
data.Q6 %>%
  filter(A003 != "Other Industry") %>%
  mutate(A003 = case_when(A003 == "Construction Industry" ~ "Service Industry",
                          A003 == "Mining / Metal" ~ "Manufacturing Industry",
                          A003 == "Education / Further Education" ~ 
                            "Service Industry",
                          A003 == "Chemistry / Pharmaceuticals" ~
                            "Manufacturing Industry",
                          A003 == "Electrical Engineering" ~
                            "Manufacturing Industry",
                          A003 == "Energy / Water" ~ "Service Industry", 
                          A003 == "Vehicle Manufacturing / Supplier" ~
                            "Manufacturing Industry",
                          A003 == "Finance / Insurance" ~ "Service Industry", 
                          A003 == "Hospitality / Retail" ~ "Service Industry",
                          A003 == "Health / Social Services" ~ "Service Industry",
                          A003 == "Real Estate / Housing" ~ "Service Industry",
                          A003 == "Trade / Commerce" ~ "Service Industry", 
                          A003 == "Information Technology / Communication" ~
                            "Service Industry", 
                          A003 == "Art / Entertainment / Recreation" ~
                            "Service Industry",
                          A003 == "Agriculture / Forestry" ~ "Service Industry", 
                          A003 == "Mechanical Engineering" ~ 
                            "Manufacturing Industry",
                          A003 == "Food Industry" ~ "Manufacturing Industry", 
                          A003 == "Traffic / Logistics / Transportation" ~
                            "Service Industry",
                          A003 == "Other Service Industry" ~ "Service Industry", 
                          A003 == "Other Manufacturing Industry" ~
                            "Manufacturing Industry"))%>%
 
  arrange(E002) %>%
  ggplot(aes(x=A003, y = abs_frequency, fill=factor(E002)))+
  geom_bar(position="fill",stat="identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
  labs(x = "Type of Industry",
       y = "Percent of companies",
       title = "Frequency of corporate volunteering activities
compared to the industry type") +
  theme_minimal()+
  theme(title=element_text(size = 15),
        axis.title = element_text(size = 15),
        axis.text.x = element_text(colour="black",angle = 45, hjust = 1,size = 12),
        axis.text.y = element_text(colour="black",size = 12),
        legend.text= element_text(size = 14),
        legend.title=element_text(size = 15))+
  scale_fill_brewer(name="Frequency of volunteering:",
                      breaks=c(1,2,3,4,5),
                      labels=c("irregular","once a year","once in a six months",                           "once per quarter","more often than once a month"),
                      palette = "GnBu")

 ggsave("6.3question.jpeg",device = "jpeg", width = 9, height = 6)

```



