---
title: "Question 2"
author: "Daria Moiseeva"
date: "2023-11-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r reading data, include=FALSE}
library(readxl)
data <- read_xlsx("MUE.2022.for.LMU.xlsx")
data
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(gridExtra)
library(patchwork)

cbPalette <- c("#999999","#56B4E9", "#CC79A7","#F0E442", "#0072B2", "#D55E00", "#E69F00" )
```


```{r  data.Q}
data.Q <- data %>%
  select(class,E002)%>%
  filter(!is.na(E002)) %>%
  group_by(class) %>%
  mutate(n_companies = length(class))%>%
  group_by(class,E002) %>%
  mutate(n_frequency = length(E002)) %>%
  group_by(class,E002) %>%
  mutate(percent= n_frequency / n_companies)%>%
  distinct()%>%
  arrange(class,E002)

ggplot(data.Q, aes(x = factor(class, levels = c("Kleine Unternehmen","Mittlere Unternehmen","Großunternehmen"),labels = c("Small","Middle","Big")), y = percent, fill = factor(E002))) +
geom_bar(stat = "identity",position = "dodge") +
labs(x = "Size of a company", y = "Percent of companies engaged", 
title = "Frequency of corporate volunteering activities against
the size of a company") +
scale_fill_manual(name ="Frequency of engagement :",
labels = c("Weiß nicht","Unregelmäßig","Einmal pro Jahr","Einmal pro Halbjahr","Einmal pro Quartal","Häufiger als einmal pro Monat"),
values = cbPalette)

```
